[package]
name = "siss-a2a-dispatcher"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
uuid.workspace = true
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true
tokio.workspace = true
siss-memory-plane = { path = "../siss-memory-plane" }
siss-context-cartography = { path = "../siss-context-cartography" }
siss-graph-core = { path = "../siss-graph-core" }
