plugins {
    id 'java-library'
}

dependencies {
    implementation project(':aeib-core')
    implementation project(':aeib-crypto')
    implementation project(':aeib-runtime')
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.18.2'
    testImplementation project(':aeib-core')
    testImplementation project(':aeib-crypto')
    testImplementation project(':aeib-runtime')
    testImplementation project(':aeib-verifier')
    testImplementation 'com.fasterxml.jackson.core:jackson-databind:2.18.2'
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.10.1'
    testImplementation 'org.junit.jupiter:junit-jupiter-params:5.10.1'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.10.1'
}

test {
    useJUnitPlatform()
}
