[package]
name = "siss-os-sidecar"
edition.workspace = true
version.workspace = true

[dependencies]
siss-enclave = { path = "../siss-enclave" }
anyhow = "1"
async-trait = "0.1"
serde = { workspace = true }
tokio = { workspace = true }
thiserror = { workspace = true }
sysinfo = "0.30"

[target.'cfg(target_os = "macos")'.dependencies]
libc = "0.2"
objc2 = "0.5"
objc2-metal = "0.2"

[dev-dependencies]
