[package]
name = "siss-event-log"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
chrono.workspace = true
tokio = { workspace = true, features = ["sync"] }
sqlx.workspace = true
futures.workspace = true
thiserror.workspace = true

[dev-dependencies]
testcontainers.workspace = true
tokio = { workspace = true, features = ["full", "test-util"] }
