[package]
name = "siss-payment"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
uuid.workspace = true
chrono = { workspace = true, features = ["serde"] }
serde = { version = "1", features = ["derive"] }
dashmap = "5.5"
parking_lot = "0.12"
sha2.workspace = true
hex.workspace = true
rand.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["rt", "macros"] }
