[package]
name = "siss-stream6-usa-creator"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
uuid = { workspace = true }
chrono = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
sqlx = { workspace = true }
tracing = { workspace = true }
dashmap = "5.5"
siss-layer00 = { path = "../siss-layer00" }

[dev-dependencies]
tokio = { workspace = true, features = ["test-util"] }
