[package]
name = "siss-ui-server"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "siss-ui-server"
path = "src/main.rs"

[dependencies]
axum.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
chrono.workspace = true
tower.workspace = true
http-body-util.workspace = true

[dev-dependencies]
